### ISSUE TITLE
Error When create project

### ISSUE THREAD

**Issue by inoex135** [laravolt/laravolt-project#2]
I got this error when do create-project command: 
> composer create-project laravolt/laravolt

> > @php artisan key:generate
> Application key [base64:kYstXe/XrAXminJt3ov9r8O0gCfctgCBn9pydeLMVFs=] set successfully.
> > @php artisan storage:link
> The [public/storage] directory has been linked.
> > @php artisan laravolt:link-assets
> 
>    ErrorException  : symlink(): No such file or directory
> 
>   at /Users/wisnov/workspace/laravolt/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:228
>     224|      */
>     225|     public function link($target, $link)
>     226|     {
>     227|         if (! windows_os()) {
>   > 228|             return symlink($target, $link);
>     229|         }
>     230| 
>     231|         $mode = $this->isDirectory($target) ? 'J' : 'H';
>     232|
> 
>   Exception trace:
> 
>   1   symlink("/Users/wisnov/workspace/laravolt/vendor/laravolt/ui/src/../public", "/Users/wisnov/workspace/laravolt/public/laravolt")
>       /Users/wisnov/workspace/laravolt/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:228
> 
>   2   Illuminate\Filesystem\Filesystem::link("/Users/wisnov/workspace/laravolt/vendor/laravolt/ui/src/../public", "/Users/wisnov/workspace/laravolt/public/laravolt")
>       /Users/wisnov/workspace/laravolt/vendor/laravolt/ui/src/AssetLinkCommand.php:35
> 
>   Please use the argument -v to see more details.
> Script @php artisan laravolt:link-assets handling the post-create-project-cmd event returned with error code 1
>

**Comment by uyab** [comment]
Fixed in 0.2
