### ISSUE TITLE
Error management user

### ISSUE THREAD

**Issue by rezgui** [laravolt/laravolt-project#4]
after install laravolt ,
after lunch migrate db with fresh tables
i can't seed 
raison for this is 'password_last_set' field not defined in users table

**Comment by anandiamy** [comment]
You need to run this artisan command :
`php artisan vendor:publish --tag=migrations --provider="Laravolt\Password\ServiceProvider"`

the use of the above command is to export the migration file from `laravolt/password`

**Comment by uyab** [comment]
Fixed in 0.4 by including all migrations and config files
